build(wrappers/python): add python build scripts for GH Actions

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -87,6 +87,67 @@ jobs:
         env:
           CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
 
+  publish-pypi-packages:
+    name: Publish PyPi packages
+    runs-on: ubuntu-latest # ok since none of the scripts depend on version-specific features
+    defaults:
+      run:
+        shell: bash
+    needs: publish-github-release
+    steps:
+      - name: Clone
+        uses: actions/checkout@v4
+      - name: Download CLI binaries
+        uses: actions/download-artifact@v4
+        with:
+          pattern: release-*
+          merge-multiple: true
+          path: ./wrappers/python/vendor
+      - name: Set up python 3.12
+        uses: actions/setup-python@v5
+        with:
+          python-version: "3.12"
+      - name: Set up poetry
+        run: bash ./wrappers/python/scripts/ci/github/setup_poetry.sh
+      - name: cache venv
+        uses: actions/cache@v4
+        with:
+          path: .venv
+          key: ${{ runner.os }}-poetry-3.12-${{ hashFiles('**/poetry.lock') }}
+      - name: Install dev dependencies
+        run: bash ./wrappers/python/scripts/ci/github/install_dev_dependencies.sh
+        working-directory: ./wrappers/python
+      - name: debug
+        run: |
+          set -x
+          echo "$PATH" | tr ':' '\n'
+          command -v python
+          command -v python3
+          command -v poetry || echo "missing poetry"
+          stat .venv/bin/python
+          .venv/bin/python --version
+      - name: package binaries
+        working-directory: ./wrappers/python
+        run: |
+          export PATH="$PWD/.venv/bin:$PATH"
+          python3 -m scripts.build.all ./vendor # should take ~30s
+      - name: package python api
+        run: |
+          export PATH="$PWD/.venv/bin:$PATH"
+          python3 -m scripts.build.api_package
+      - name: Archive dist
+        uses: actions/upload-artifact@v4
+        with:
+          path: dist
+          name: python-packages
+          if-no-files-found: error
+      # TODO: once we have a TEST_PYPI_TOKEN, test publishing the packages.
+      # - name: Publish python packages
+      #   working-directory: ./wrappers/python
+      #   run: |
+      #     export PATH="$PWD/.venv/bin:$PATH"
+      #     ./scripts/publish_to_test_pypi.sh
+
   publish-npm-package:
     name: Publish NPM packages
     runs-on: ubuntu-20.04
@@ -144,6 +205,7 @@ jobs:
           npm publish --tag $GIT_TAG --access public
         env:
           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
+
 
   publish-binary-npm-packages:
     name: Publish NPM binaries
